"""
APEX Framework - All Systems Running
======================================

Running Services Summary:
"""

print("\n" + "="*70)
print("APEX FRAMEWORK - ALL SYSTEMS ACTIVE".center(70))
print("="*70)

print("\n[1] PROJECT DEMO - TEST RESULTS")
print("-" * 70)
print("Status: PASSED")
print("\nModules Tested (10/10):")
print("  [OK] Configuration Module")
print("  [OK] Data Ingestion Module")
print("  [OK] Preprocessing Module (with fallbacks)")
print("  [OK] Model Registry")
print("  [OK] Monitoring & Drift Detection")
print("  [OK] Pipeline Orchestration")
print("  [OK] AutoML Selector")
print("  [OK] Utilities & Progress Display")
print("  [OK] Data Adapters (PBTL)")
print("  [OK] Frontend Module (Streamlit)")

print("\n" + "="*70)
print("[2] API SERVER - RUNNING")
print("-" * 70)
print("Status: ACTIVE")
print("URL: http://localhost:8001")
print("API Docs: http://localhost:8001/docs")
print("Port: 8001")
print("Framework: FastAPI + Uvicorn")
print("\nAvailable Endpoints:")
print("  GET  /              Root endpoint")
print("  GET  /health        Health check")
print("  GET  /config        Load configuration")
print("  POST /predict       Make predictions")
print("  GET  /modules       List modules")
print("  GET  /docs          Interactive API documentation")

print("\n" + "="*70)
print("[3] STREAMLIT FRONTEND - RUNNING")
print("-" * 70)
print("Status: ACTIVE")
print("URL: http://localhost:8502")
print("Local: http://localhost:8502")
print("Network: http://10.10.3.60:8502")
print("Port: 8502")
print("Framework: Streamlit")
print("\nFeatures:")
print("  * Navigation sidebar")
print("  * Home page")
print("  * Model Management")
print("  * Inference interface")
print("  * Data visualization")

print("\n" + "="*70)
print("PROJECT STATISTICS")
print("-" * 70)
print("Total Python Files: 39")
print("Total Code Size: 52,750 bytes")
print("Number of Modules: 10")
print("Total Classes/Functions: 50+")
print("Git Repository: https://github.com/abhiramsb225-bit/apex2")

print("\n" + "="*70)
print("OPEN IN YOUR BROWSER")
print("-" * 70)
print("\n1. API Server & Docs:")
print("   http://localhost:8001/docs")
print("\n2. Streamlit Web Interface:")
print("   http://localhost:8502")

print("\n" + "="*70)
print("RUNNING SERVICES:")
print("-" * 70)
print("\n✓ API Server (Port 8001)")
print("✓ Streamlit App (Port 8502)") 
print("✓ All Modules Tested & Verified")

print("\n" + "="*70)
print("COMMAND REFERENCE")
print("-" * 70)
print("\nStart API Server:")
print("  python run_api.py")
print("\nStart Streamlit Frontend:")
print("  python -m streamlit run frontend/app_enhanced.py")
print("\nRun Project Demo:")
print("  python run_project_demo.py")

print("\n" + "="*70)
print("PROJECT STATUS: FULLY OPERATIONAL".center(70))
print("="*70 + "\n")
